# Generated by Django 5.1.6 on 2025-03-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('opened', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='phishingemail',
            name='sent_to',
        ),
        migrations.DeleteModel(
            name='ClickTracking',
        ),
        migrations.DeleteModel(
            name='PhishingEmail',
        ),
        migrations.DeleteModel(
            name='TargetUser',
        ),
    ]
