# Generated by Django 5.1.6 on 2025-03-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_emailtracking_remove_phishingemail_sent_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtracking',
            old_name='clicked',
            new_name='clicked_link',
        ),
        migrations.RenameField(
            model_name='emailtracking',
            old_name='opened',
            new_name='passed_test',
        ),
        migrations.RenameField(
            model_name='emailtracking',
            old_name='timestamp',
            new_name='test_date',
        ),
        migrations.RenameField(
            model_name='emailtracking',
            old_name='email',
            new_name='user_email',
        ),
    ]
