# Generated by Django 5.1.6 on 2025-04-17 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0003_rename_clicked_emailtracking_clicked_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('opened', 'Opened'), ('clicked', 'Clicked'), ('reported', 'Reported'), ('ignored', 'Ignored')], max_length=20)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhishingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('email_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('phishing_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.phishingemail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('email_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailTracking',
        ),
        migrations.AddField(
            model_name='emailinteraction',
            name='email_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.emaillog'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.phishingemail'),
        ),
    ]
